/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.heritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {


    @Test
    public void reviewTest(){
        Restaurant numberOne = new Restaurant("numberOne" , 5 , "$$");
        Review review1 = new Review("This is good resturant" , "hamzh" , 4);
        Review review2 = new Review("This is bad resturant" , "ahmad" , 1);
        Review review3 = new Review("This is good resturant" , "mohammed" , 1);
        numberOne.addReview(review1);
        numberOne.addReview(review2);
        numberOne.addReview(review3);

        assertEquals(2, numberOne.getStars());

    }


}
