/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.List;
public class LibraryTest {
    @Test
    void calculateAverage() {

        int[] arr = {1, 2, 3};
        int testResult = Library.calculateAverage(arr);
        assertEquals(2, testResult);
    }

    @Test
    void avgArrOfArr() {
        int[][] arr = {{66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}};
        int[] testResult = Library.avgArrOfArr(arr);
        int[] testExpec = {63, 63, 57, 57};
        assertArrayEquals(testExpec, testResult);

    }

    @Test
    void containsDuplicates() {
        int[] arr = {1, 2, 3, 4, 5};
        boolean testResult = Library.containsDuplicates(arr);
        assertFalse(testResult);
    }

    @Test
    void roll() {
        boolean test = true;
        int n = 6;
        int[] rollValur = Library.roll(n);
        for (int elemnt :
                rollValur) {
            if (elemnt < 0 || elemnt > 6) {
                test = false;
            }
        }
        if (rollValur.length != n) {
            test = false;
        }
        assertTrue(test);
    }
    @Test
    void tally(){
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Shrub");
        votes.add("Shrub");
        votes.add("Shrub");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String winner = Library.tally(votes);
        assertEquals("Shrub", winner);
    }
    @Test
    void wetherAnalyzer(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        String result = Library.wetherAnalyzer(weeklyMonthTemperatures);
        String exp = "High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69\n" ;
        assertEquals(exp , result);
    }
}
