/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;


public class App {

    public static void main(String[] args) {
        String path = String.valueOf(FileSystems.getDefault().getPath(System.getProperty("user.dir"), "app/src/main/resources/gates.js"));
        int errLineNumber = fileReader(path);
        System.err.println("Line "+ errLineNumber + ": Missing semicolon.");
    }

    public static int fileReader(String path){

        Path bufferPath = Paths.get(path);
        int counter = 0 ;
        try {
            BufferedReader reader = Files.newBufferedReader(bufferPath);
            String line = reader.readLine();
            while(line != null){
                counter++;
                if(!line.isEmpty() && !line.contains("if") && !line.contains("{") && !line.contains("}")&& !line.contains("else") ){
                    if(!line.contains(";")){
                        System.out.println("Line "+ counter + ": Missing semicolon.");
                        break;
                    }
                }
                line = reader.readLine();
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        return counter ;
    }

}
