/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;


public class App {

    public static void main(String[] args) {
        String path = String.valueOf(FileSystems.getDefault().getPath(System.getProperty("user.dir"), "app/src/main/resources/gates.js"));
        int errLineNumber = fileReader(path);
        System.err.println("Line "+ errLineNumber + ": Missing semicolon.");

        int arr[] = {10,20,30,40,50};
        int num = 30;
        int last=arr.length-1;
        binarySearch(arr,num);
    }

    public static int fileReader(String path){

        Path bufferPath = Paths.get(path);
        int counter = 0 ;
        try {
            BufferedReader reader = Files.newBufferedReader(bufferPath);
            String line = reader.readLine();
            while(line != null){
                counter++;
                if(!line.isEmpty() && !line.contains("if") && !line.contains("{") && !line.contains("}")&& !line.contains("else") ){
                    if(!line.contains(";")){
                        System.out.println("Line "+ counter + ": Missing semicolon.");
                        break;
                    }
                }
                line = reader.readLine();
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        return counter ;
    }
    public static int binarySearch(int[] arr ,int num){
        int index = 0 ;
        int len = arr.length-1;
        int mid = (index+len)/2 ;
        while (index <= len){
            if ( arr[mid] < num ){
                index = mid + 1;
            }else if ( arr[mid] == index ){
                break;
            }else{
                len = mid - 1;
            }
            mid = (index + len)/2;
        }
        return mid;
    }

}
