/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.heritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {


    @Test
    public void restReviewTest(){
        Restaurant restaurant = new Restaurant("numberOne" , 5 , "$$");
        Review review1 = new Review("This is good resturant" , "mohammed" , 1);
        restaurant.addReview(review1);
        assertEquals(3, restaurant.getStars());
    }
    @Test
    public void shopReviewTest(){
        Review shopReview = new Review("This is a great shop" ,"hamzh" ,  1 );
        Shop shop = new Shop("ecommerce" , 5 , "$$$" , "This is perfect shop");
        shop.addReview(shopReview);
        assertEquals(3, shop.getStars());
    }
    @Test
    public void theterReviewTest(){
        Review moviesReview = new Review("This is bad action movies" , "ahmad" , 1);
        moviesReview.setMovieName("Spider-man");
        Theater theater = new Theater("number1" , 5 );
        theater.addReview(moviesReview);
        assertEquals(3, theater.getStars());
    }


}
