/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.class02;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

//    @Test
//    void calculateAverage(){
//
//        int[] arr = {1,2,3};
//        int testResult = App.calculateAverage(arr);
//        assertEquals(2 ,testResult);
//    }
//
//    @Test
//    void avgArrOfArr(){
//
//        int[][]arr = { {66, 64, 58, 65, 71, 57, 60},
//                {57, 65, 65, 70, 72, 65, 51},
//                {55, 54, 60, 53, 59, 57, 61},
//                {65, 56, 55, 52, 55, 62, 57}};
//        int[] testResult = App.avgArrOfArr(arr);
//        int[] testExpec = {63,63,57,57};
//        assertArrayEquals(testExpec, testResult);
//
//    }
//
//    @Test
//    void containsDuplicates(){
//        int[] arr = {1,2,3,4,5};
//        boolean testResult = App.containsDuplicates(arr);
//        assertFalse(testResult);
//    }


}
